"""Shared interfaces — no implementations, no upward imports."""

from __future__ import annotations

from collections.abc import AsyncIterator, Awaitable, Callable
from typing import TYPE_CHECKING, Protocol

from melody.models import Album, PlaybackStatus, Playlist, Track

if TYPE_CHECKING:
    from melody.playback.queue import QueueManager


class ISubsonicClient(Protocol):
    """Backend-agnostic Subsonic API client."""

    async def search_tracks(self, query: str, limit: int = 20) -> list[Track]: ...

    async def search_albums(self, query: str, limit: int = 20) -> list[Album]: ...

    async def search_playlists(self, query: str, limit: int = 20) -> list[Playlist]: ...

    async def get_album(self, album_id: str) -> Album: ...

    async def get_playlist(self, playlist_id: str) -> Playlist: ...

    async def get_song(self, song_id: str) -> Track: ...

    def stream_url(self, song_id: str) -> str: ...

    async def open_stream(self, song_id: str) -> tuple[str, AsyncIterator[bytes]]: ...

    async def stream(self, song_id: str) -> AsyncIterator[bytes]: ...

    async def close(self) -> None: ...


class IChannelSession(Protocol):
    """Per-channel bot session surface used by the command layer."""

    channel_id: int

    @property
    def queue(self) -> QueueManager: ...

    @property
    def playback_status(self) -> PlaybackStatus: ...

    async def send_message(self, message: str) -> None: ...

    async def ensure_joined(self) -> bool: ...

    async def start_playback(self, *, announce: bool = True) -> None: ...

    def schedule_playback(self, *, announce: bool = True) -> None: ...

    async def fast_disconnect(self) -> None: ...

    def cancel_playback_tasks(self) -> None: ...

    def begin_stop(self, *, clear_all: bool = False) -> None: ...

    def schedule_stop_drain(self) -> None: ...

    def prepare_for_shutdown(self) -> None: ...

    async def stop_playback(self, *, clear_all: bool = False) -> None: ...

    async def replace_playback(self) -> None: ...

    def pause(self) -> None: ...

    async def resume(self) -> None: ...

    async def skip_next(
        self,
        *,
        notify: Callable[[str], Awaitable[None]] | None = None,
    ) -> None: ...

    async def skip_back(
        self,
        *,
        notify: Callable[[str], Awaitable[None]] | None = None,
    ) -> None: ...

    @property
    def volume_percent(self) -> int: ...

    def set_volume_percent(self, percent: int) -> None: ...

    def update_human_count(self, count: int) -> None: ...
