"""Shared interfaces — no implementations, no upward imports."""

from __future__ import annotations

from collections.abc import AsyncIterator
from typing import TYPE_CHECKING, Protocol

from melody.models import Playlist, Track

if TYPE_CHECKING:
    from melody.playback.queue import QueueManager


class ISubsonicClient(Protocol):
    """Backend-agnostic Subsonic API client."""

    async def search_tracks(self, query: str, limit: int = 20) -> list[Track]: ...

    async def search_playlists(self, query: str, limit: int = 20) -> list[Playlist]: ...

    async def get_playlist(self, playlist_id: str) -> Playlist: ...

    async def get_song(self, song_id: str) -> Track: ...

    def stream_url(self, song_id: str) -> str: ...

    async def stream(self, song_id: str) -> AsyncIterator[bytes]: ...

    async def close(self) -> None: ...


class IChannelSession(Protocol):
    """Per-channel bot session surface used by the command layer."""

    @property
    def queue(self) -> QueueManager: ...

    async def send_message(self, message: str) -> None: ...

    async def ensure_joined(self) -> None: ...

    async def start_playback(self) -> None: ...

    async def stop_playback(self, *, clear_all: bool = False) -> None: ...

    def pause(self) -> None: ...

    async def resume(self) -> None: ...

    async def skip_next(self) -> None: ...

    async def skip_back(self) -> None: ...
